---
title: "Investigate new IPSSR CCRS score"
author: "Christelle Colin-Leitzinger"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: kable
  word_document:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
```

```{r library, echo = FALSE}
library(tidyverse)
library(gtsummary)
library(survminer)
library(survival)
theme_gtsummary_compact()
theme_set(theme_classic())
```


```{r load}
mds_data <- read_rds(paste0(here::here(), 
                            "/data/processed_data",
                            "/MDSSerialAnalysis_NewScore_20251203.rds")) %>% 
  mutate(cytogenetics_group_final = case_when(
    from_cytogenetics_discordant_file_ipssr_total_new.x == 99            ~ NA_character_,
    !is.na(from_cytogenetics_discordant_file_cyto_group_reviewed.x)      ~ str_to_sentence(from_cytogenetics_discordant_file_cyto_group_reviewed.x),
    TRUE                                                                 ~ mds_cyto_r_ips_prog_sub_g_recoded
  )) %>% 
  mutate(across(c("blast_final"), ~ case_when(
    . <= 2         ~ 0,
    . > 2 &
      . < 5        ~ 1,
    . >= 5 &
      . <= 10      ~ 2,
    . > 10         ~ 3
  ), .names = "{.col}_ipssr_point")) %>% 
  mutate(across(ends_with("_ipssr_point"), ~ as.character(.))) %>% 
  mutate(across(ends_with("_ccrs_point"), ~ as.character(.)))
```

# IPSSR in MDS
```{r}
mds_data %>% 
  filter(!is.na(ipssr_2cat_for_series)) %>% 
  ggplot(aes(x = lab_dt, y = ipssr_score_for_series))+
  geom_point()

mds_data %>% 
  filter(!is.na(ipssr_2cat_for_series)) %>% 
  ggplot(aes(x = lab_dt, y = ipssr_2cat_for_series))+
  geom_point()
```


# CCRS in CCUS and ICUS/IDUS
```{r}
mds_data %>% 
  filter(!is.na(ccrs_3cat_for_series)) %>% 
  ggplot(aes(x = lab_dt, y = ccrs_score_for_series))+
  geom_point()

mds_data %>% 
  filter(!is.na(ccrs_3cat_for_series)) %>% 
  ggplot(aes(x = lab_dt, y = ccrs_3cat_for_series))+
  geom_point()
```


```{r}
a <- mds_data %>% 
  select(mdsepid, lab_dt, ends_with("_ipssr_point"), ipssr_score_for_series,
         ends_with("_ccrs_point"), ccrs_score_for_series)
```

# Cox analysis
## For MDS
```{r}
mdsp <- mds_data %>% 
  filter(final_class == "MDS") %>% 
  arrange(mdsepid, lab_dt) %>% 
  distinct(mdsepid, .keep_all = TRUE)
a <- mdsp %>% select(ends_with("_ipssr_point"))
```
### At baseline
```{r OS initial death}
tbl_1 <- tbl_uvregression(
  mdsp,
  method = coxph,
  y = Surv(time = os_time_days_in_fup_file, event = os_event_fup),
  exponentiate = TRUE,
  include = c("cyto_group_ipssr_point", "blast_final_ipssr_point", 
              "series_lab_result_hgb_ipssr_point", "series_lab_result_plt_ipssr_point",
              "series_lab_result_anc_ipssr_point"),
  # pvalue_fun = label_style_pvalue(digits = 2)
  ) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()


tbl_2 <-
  coxph(Surv(time = mdsp$os_time_days_in_fup_file,
             event = mdsp$os_event_fup) ~ cyto_group_ipssr_point + blast_final_ipssr_point + 
          series_lab_result_hgb_ipssr_point + series_lab_result_plt_ipssr_point +
          series_lab_result_anc_ipssr_point,
        data = mdsp) %>%
  tbl_regression(exponentiate = TRUE) %>%
  bold_p(t = 0.05) %>%
  add_nevent(location = "level") %>% add_n(location = "level")

tbl_merge(list(tbl_1, tbl_2), tab_spanner = c("**Univariable**", "**Multivariable**"))
```


## For CCUS
```{r}
ccusp <- mds_data %>% 
  filter(final_class == "CCUS") %>% 
  arrange(mdsepid, lab_dt) %>% 
  distinct(mdsepid, .keep_all = TRUE)
```
### At baseline
```{r OS initial death}
tbl_1 <- tbl_uvregression(
  ccusp,
  method = coxph,
  y = Surv(time = os_time_days_in_fup_file, event = os_event_fup),
  exponentiate = TRUE,
  include = c("number_of_mutation_for_serie_ccrs_point", 
              "series_lab_result_plt_ccrs_point",
              "slicing_mutation_for_serie_ccrs_point"),
  # pvalue_fun = label_style_pvalue(digits = 2)
  ) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()


tbl_2 <-
  coxph(Surv(time = ccusp$os_time_days_in_fup_file,
             event = ccusp$os_event_fup) ~ number_of_mutation_for_serie_ccrs_point + 
          series_lab_result_plt_ccrs_point +
          slicing_mutation_for_serie_ccrs_point,
        data = ccusp) %>%
  tbl_regression(exponentiate = TRUE) %>%
  bold_p(t = 0.05) %>%
  add_nevent(location = "level") %>% add_n(location = "level")

tbl_merge(list(tbl_1, tbl_2), tab_spanner = c("**Univariable**", "**Multivariable**"))
```


# Time dependent cox analysis
## For MDS
```{r}
mdsp <- mds_data %>% 
  filter(final_class == "MDS") %>% 
  arrange(mdsepid, lab_dt) %>% 
  distinct(mdsepid, .keep_all = TRUE) %>% 
  mutate(time = round(os_time_fup_months))

ids <- unique(mdsp$mdsepid)
time_dat <- tibble(mdsepid = c(rep(ids, 3)),
                     tstart = c(rep(0, 510), rep(90, 510), rep(270, 510)),
                   tend = c(rep(90, 510), rep(270, 510), rep(450, 510))
                   ) %>% 
  arrange(mdsepid, tstart)

mdsp_ <- mdsp %>% 
  full_join(time_dat, ., by = "mdsepid")
  select(mdsepid, cyto_group_ipssr_point, blast_final_ipssr_point, 
         bm_blast_pct_basline,
         lab_result_absolute_neutrophil_count_anc_blood,
         lab_result_hemoglobin_blood,
         lab_unit_platelets_blood,
         
         bm_blast_pct_ipssr_point,
         
         
         
              series_lab_result_hgb_ipssr_point, series_lab_result_plt_ipssr_point,
              series_lab_result_anc_ipssr_point, 
         os_time_fup_months, os_event_fup)


```

Every 6 months
```{r}
newdata <- survSplit(Surv(time = time, event = os_event_fup) ~., 
                     data = mdsp , cut=c(36, 72, 120, 168, 270), 
                     # episode= "tgroup", 
                     id="mdsepid")

timedep_fit <- coxph(Surv(tstart, time, event) ~ debulking + stage + agedx:strata(tgroup), data=newdata)
coxph(Surv(time1, time2, status) ~ age + creatinine, data=mydata)

veteran
survSplit(Surv(time, status) ~., veteran,
                   cut=c(60, 120), episode ="timegroup")




```





